### Passo 1 - Importar Arquivos e Bibliotecas

In [1]:
senha_app = "pgxv kaxz zgho gtos"

In [2]:
import pandas as pd
from pathlib import Path 
from email.message import EmailMessage
import smtplib
caminho_importacao = Path("Bases de Dados")

email_gerente = pd.read_excel(caminho_importacao / "Emails.xlsx")
lojas = pd.read_csv(caminho_importacao / "Lojas.csv", encoding="latin1", sep=";")
vendas = pd.read_excel(caminho_importacao / "Vendas.xlsx")

display(email_gerente)
display(lojas)
vendas = vendas.merge(lojas, on="ID Loja")
display(vendas)

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,pythonimpressionador+helena@gmail.com
1,Shopping Midway Mall,Alice,pythonimpressionador+alice@gmail.com
2,Norte Shopping,Laura,pythonimpressionador+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,pythonimpressionador+manuela@gmail.com
4,Shopping União de Osasco,Valentina,pythonimpressionador+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,pythonimpressionador+sophia@gmail.com
6,Rio Mar Recife,Isabella,pythonimpressionador+isabella@gmail.com
7,Salvador Shopping,Heloisa,pythonimpressionador+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,pythonimpressionador+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,pythonimpressionador+julia@gmail.com
10,Ribeirão Shopping,Lorena,pythonimpressionador+lorena@gmail.com
11,Shopping Morumbi,Livia,pythonimpressionador+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,pythonimpressionador+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,pythonimpressionador+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,pythonimpressionador+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,pythonimpressionador+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,pythonimpressionador+arthur@gmail.com
17,Shopping Recife,Heitor,pythonimpressionador+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,pythonimpressionador+bernardo@gmail.com
19,Shopping SP Market,Davi,pythonimpressionador+davi@gmail.com
20,Shopping Eldorado,Theo,pythonimpressionador+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,pythonimpressionador+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,pythonimpressionador+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,pythonimpressionador+pedro@gmail.com
24,Shopping Barra,Benjamin,pythonimpressionador+benjamin@gmail.com
25,Diretoria,Diretoria,pythonimpressionador+diretoria@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,2,2019-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2019-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
...,...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204,Center Shopping Uberlândia
100995,69996,2019-12-26,17,Mochila,4,270,1080,Center Shopping Uberlândia
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87,Center Shopping Uberlândia
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2019-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

### Passo 2 - Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [3]:
dia_indicador = vendas["Data"].max()


dic_lojas = {}

for loja in lojas["Loja"]:
    dic_lojas[loja] = vendas.loc[vendas["Loja"]==loja, :]


gerente = email_gerente.loc[email_gerente["Loja"]=="Iguatemi Esplanada", "Gerente"].values[0]
print(gerente)

Helena

### Passo 3 - Salvar a planilha na pasta de backup

In [4]:
caminho_backup = Path(r"Backup Arquivos Lojas")
#lista_arquivos = caminho_backup.iterdir()
#lista_nomes = [for arquivo ]


for loja in dic_lojas:
    pastas_lojas = caminho_backup / loja
    pastas_lojas.mkdir(exist_ok=True)

    nome_arquivo = f"{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx"
    arquivos = pastas_lojas / nome_arquivo
    dic_lojas[loja].to_excel(arquivos, index=False)

In [5]:
# metas 
meta_faturamento_anual = 1650000
meta_faturamento_dia = 1000

meta_produtos_anual = 120
meta_produtos_dia = 4

meta_ticket_medio_anual = 500
meta_ticket_medio_dia = 500

### Passo 4 - Calcular o indicador para 1 loja

In [ ]:
email_remetente = "lucasrossi1422@gmail.com"
senha_aplicativo = (
    senha_app  
)



print("Conectando ao servidor de e-mail...")
servidor = smtplib.SMTP("smtp.gmail.com", 587)
servidor.starttls() 
servidor.login(email_remetente, senha_aplicativo)
print("Conexão estabelecida com sucesso!\n")



for loja in dic_lojas:
    vendas_anuais = dic_lojas[loja]
    vendas_dia = vendas_anuais.loc[vendas_anuais["Data"]==dia_indicador, :]

    faturamento_anual = vendas_anuais["Valor Final"].sum() 
    faturamento_dia = vendas_dia["Valor Final"].sum()

    produtos_anual = len(vendas_anuais["Produto"].unique())  
    produtos_dia = len(vendas_dia["Produto"].unique())

    ticket_medio_anual = vendas_anuais[["Código Venda", "Valor Final"]].groupby("Código Venda").sum()
    ticket_medio_anual = ticket_medio_anual["Valor Final"].mean()

    ticket_medio_dia = vendas_dia[["Código Venda", "Valor Final"]].groupby('Código Venda').sum()
    ticket_medio_dia = ticket_medio_dia["Valor Final"].mean()

    if faturamento_anual > meta_faturamento_anual:
        cor_faturamento_anual = "green"
    else:
        cor_faturamento_anual = "red"

    if faturamento_dia > meta_faturamento_dia:
        cor_faturamento_dia = "green"
    else:
        cor_faturamento_dia = "red"

    if produtos_anual > meta_produtos_anual:
        cor_produtos_anual = "green"
    else:
        cor_produtos_anual = "red"

    if produtos_dia > meta_produtos_dia:
        cor_produtos_dia = "green"
    else:
        cor_produtos_dia = "red"

    if ticket_medio_anual > meta_ticket_medio_anual:
        cor_ticket_anual = "green"
    else:
        cor_ticket_anual = "red"

    if ticket_medio_dia > meta_ticket_medio_dia:
        cor_ticket_dia = "green"
    else:
         cor_ticket_dia = "red"


    nome_arquivo = f"{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx"
    caminho_arquivo = caminho_backup / loja / nome_arquivo


    email_destinatario = email_gerente.loc[email_gerente["Loja"]==loja, "E-mail"].values[0]
    nome_gerente = email_gerente.loc[email_gerente["Loja"]==loja, "Gerente"].values[0]
    
    corpo_email = f"""
    <p>Bom dia, {nome_gerente}</p>
    
    <p>O resultado de ontem ({dia_indicador.strftime('%d/%m/%Y')}) da Loja {loja} foi:</p>
    
    <table>
  <thead>
    <tr>
      <th scope="col">Indicadores</th>
      <th scope="col">Valor dia</th>
      <th scope="col">Meta Dia</th>
      <th scope="col">Cenário Dia</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Faturamento</th>
      <td>{faturamento_dia:,.2f}</td>
      <td>{meta_faturamento_dia:,.2f}</td>
      <td><span style="color: {cor_faturamento_dia}; font-size: 32px;">●</span></td>
    </tr>
    <tr>
      <th scope="row">Produtos</th>
      <td>{produtos_dia}</td>
      <td>{meta_produtos_dia}</td>
      <td><span style="color: {cor_produtos_dia}; font-size: 32px;">●</span></td>
    </tr>
    <tr>
      <th scope="row">Ticket Médio</th>
      <td>{ticket_medio_dia:,.2f}</td>
      <td>{meta_ticket_medio_dia:,.2f}</td>
      <td><span style="color: {cor_ticket_dia}; font-size: 32px;">●</span></td>
    </tr>
  </tbody>
</table>
    

       <table>
      <thead>
        <tr>
          <th scope="col">Indicadores</th>
          <th scope="col">Valor anual</th>
          <th scope="col">Meta anual</th>
          <th scope="col">Cenário anual</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Faturamento</th>
          <td>{faturamento_anual:,.2f}</td>
          <td>{meta_faturamento_anual:,.2f}</td>
          <td><span style="color: {cor_faturamento_anual}; font-size: 32px;">●</span></td>
        </tr>
        <tr>
          <th scope="row">Produtos</th>
          <td>{produtos_anual}</td>
          <td>{meta_produtos_anual}</td>
          <td><span style="color: {cor_produtos_anual}; font-size: 32px;">●</span></td>
        </tr>
        <tr>
          <th scope="row">Ticket Médio</th>
          <td>{ticket_medio_anual:,.2f}</td>
          <td>{meta_ticket_medio_anual:,.2f}</td>
          <td><span style="color: {cor_ticket_anual}; font-size: 32px;">●</span></td>
        </tr>
      </tbody>
    </table>

    <p>Segue em anexo a planilha com todos os dados para mais detalhes.<br>
    Qualquer dúvida, estou à disposição.</p>
    
    <p>Att.,<br>
    Lucas</p>
    """
    email = EmailMessage()
    email["Subject"] = (
      f"OnePage Dia {dia_indicador.strftime('%d/%m/%Y')} - Loja {loja}"
  )
    email["From"] = email_remetente
    email["To"] = email_destinatario
    
      
    email.set_content(corpo_email, subtype="html"
          
      )
    
      
    if caminho_arquivo.exists():
        with open(caminho_arquivo, "rb") as arquivo:
          dados_arquivo = arquivo.read()
          email.add_attachment(
              dados_arquivo,
              maintype="application",
              subtype="octet-stream",
              filename=nome_arquivo,
          )
    
        
        servidor.send_message(email)
        print(f"E-mail enviado com sucesso para a loja: {loja} ({email_destinatario})")
    else:
        print(f"Aviso: Arquivo não encontrado para a loja {loja} em {caminho_arquivo}")
    
    
servidor.quit()
print("\nProcesso de envio finalizado e conexão encerrada.")

### Passo 5 - Enviar por e-mail para o gerente

### Passo 6 - Automatizar todas as lojas

### Passo 7 - Criar ranking para diretoria

In [27]:
rank_venda = vendas[["Loja", "Valor Final"]].groupby("Loja", as_index=False).sum().sort_values(by="Valor Final", ascending=False)
#display(rank_venda)
rank_formatado = rank_venda.style.format({"Valor Final": "{:,.2f}"})
display(rank_formatado)
nome_rank = f"{dia_indicador.month}_{dia_indicador.day}_Ranking Das Lojas.xlsx"
caminho_rank = caminho_backup / nome_rank
rank_formatado.to_excel(caminho_rank, index=False)

### Passo 8 - Enviar e-mail para diretoria